# Generated by Django 3.2.6 on 2021-09-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='setCllegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president_name', models.CharField(max_length=30)),
                ('president_info', models.TextField()),
                ('president_image', models.ImageField(blank=True, null=True, upload_to='cllegeInfo/')),
            ],
            options={
                'verbose_name': 'College Information',
                'db_table': 'CllegeInfo',
            },
        ),
    ]
