# Generated by Django 3.2.6 on 2021-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_setcllegeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcllegeinfo',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='cllegeInfo/'),
        ),
        migrations.AddField(
            model_name='setcllegeinfo',
            name='principal_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setcllegeinfo',
            name='principal_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='setcllegeinfo',
            name='vice_principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='cllegeInfo/'),
        ),
        migrations.AddField(
            model_name='setcllegeinfo',
            name='vice_principal_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setcllegeinfo',
            name='vice_principal_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
