# Generated by Django 3.2.6 on 2021-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210919_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcllegeinfo',
            name='clerk_sign',
            field=models.ImageField(blank=True, null=True, upload_to='cllegeInfo/'),
        ),
        migrations.AddField(
            model_name='setcllegeinfo',
            name='principal_sign',
            field=models.ImageField(blank=True, null=True, upload_to='cllegeInfo/'),
        ),
    ]
