# Generated by Django 3.2.4 on 2021-07-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sublist',
            fields=[
                ('sub_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('optional', models.BooleanField(default=False)),
                ('fee', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Subject List',
            },
        ),
    ]
