# Generated by Django 3.2.4 on 2021-07-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sublist',
            table='SubFee',
        ),
    ]
