# Generated by Django 3.2.4 on 2021-07-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0003_auto_20210710_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteEnable', models.BooleanField(default=True, verbose_name='Enable students to pay examination fee?')),
                ('semester', models.CharField(choices=[('O', 'Odd'), ('E', 'Even')], max_length=128)),
            ],
            options={
                'verbose_name': 'Set options for exam fees payment',
                'db_table': 'SiteStatus',
            },
        ),
        migrations.AlterModelOptions(
            name='examfeepaid',
            options={'verbose_name': 'Students who have paid exam fee'},
        ),
    ]
