# Generated by Django 3.2.4 on 2021-07-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0004_auto_20210711_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublist',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
