# Generated by Django 3.2.4 on 2021-07-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0005_alter_sublist_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfeepaid',
            name='form_image',
            field=models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='examForms/', width_field='picture_width'),
        ),
        migrations.AddField(
            model_name='examfeepaid',
            name='receipt_image',
            field=models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='examReceipts/', width_field='picture_width'),
        ),
    ]
