# Generated by Django 3.2.4 on 2021-07-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0006_auto_20210713_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfeepaid',
            name='name',
            field=models.CharField(default='xyz', max_length=30),
        ),
        migrations.AddField(
            model_name='examfeepaid',
            name='register_no',
            field=models.CharField(default='m', max_length=10),
        ),
    ]
