# Generated by Django 3.2.4 on 2021-07-14 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0007_auto_20210713_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfeepaid',
            name='date_of_fee',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 13, 16, 28, 693131, tzinfo=utc)),
        ),
    ]
