# Generated by Django 3.2.4 on 2021-07-14 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0008_examfeepaid_date_of_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfeepaid',
            name='date_of_fee',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
