# Generated by Django 3.2.4 on 2021-07-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0009_alter_examfeepaid_date_of_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfeepaid',
            name='college_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='examfeepaid',
            name='month',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
