# Generated by Django 3.2.4 on 2021-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0010_auto_20210719_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_settings',
            name='Application_fee',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='site_settings',
            name='marks_card_fee',
            field=models.IntegerField(default=1),
        ),
    ]
