# Generated by Django 3.2.4 on 2021-08-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0013_auto_20210819_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfeepaid',
            name='form_image',
            field=models.FileField(blank=True, upload_to='examForms/'),
        ),
    ]
