# Generated by Django 3.2.6 on 2021-09-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0016_alter_sublist_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublist',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
