# Generated by Django 3.2.6 on 2021-09-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0017_alter_sublist_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublist',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BCom', 'BCom'), ('BSc', 'BSc'), ('BBA', 'BBA')], max_length=10),
        ),
    ]
