# Generated by Django 3.2.6 on 2021-09-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examfee', '0018_alter_sublist_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfeepaid',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
    ]
