# Generated by Django 3.2.6 on 2021-09-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_mail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
