# Generated by Django 3.2.4 on 2021-07-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('feedback', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'feedback list',
                'db_table': 'feedb_table',
            },
        ),
    ]
