# Generated by Django 3.2.4 on 2021-08-23 17:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clgfeepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('name', models.CharField(default='xyz', max_length=30)),
                ('roll_no', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_image', models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='examReceipts/', width_field='picture_width')),
                ('date_of_fee', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Students who have paid full clg fee',
                'db_table': 'clgpaid',
            },
        ),
        migrations.CreateModel(
            name='clghalffeepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('name', models.CharField(default='xyz', max_length=30)),
                ('roll_no', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_image', models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='examReceipts/', width_field='picture_width')),
                ('date_of_fee', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Students who have paid half clg fee',
                'db_table': 'clghalfpaid',
            },
        ),
        migrations.CreateModel(
            name='crslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
                ('year', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('fee', models.IntegerField()),
            ],
            options={
                'verbose_name': 'course list',
                'db_table': 'clgFee',
            },
        ),
    ]
