# Generated by Django 3.2.4 on 2021-08-25 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdfee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clgfeepaid',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='clghalffeepaid',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
