# Generated by Django 3.2.6 on 2021-09-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdfee', '0002_concession_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession_application',
            name='Reason_for_Rejection',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crslist',
            name='course',
            field=models.CharField(choices=[('1', 'BCA'), ('2', 'BCom'), ('3', 'Bsc'), ('4', 'BBA')], max_length=10),
        ),
    ]
