# Generated by Django 3.2.6 on 2021-09-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdfee', '0003_auto_20210908_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clgfeepaid',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='clghalffeepaid',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='concession_application',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='crslist',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BCOM', 'BCom'), ('BSc', 'BSc'), ('BBA', 'BBA')], max_length=10),
        ),
    ]
